name: android Ci unit test

on:
  pull_request:
    branches: [ main,develop ]

  workflow_dispatch:


jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-report
          path: app/build/reports/tests/

  instrumented-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest