name: Android-Ci-Practice

on:
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: setUp jdk
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build with grdale
        run: ./gradlew assembleDebug
