name: Android-Ci-Practice

on:
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Check android SDK
        run: echo $ANDROID_SDK_ROOT
