name: Hello yml CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:


jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello, Android CI"

  show-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Show Date
        run: date

  show-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show branch name
        run: echo "Branch ${{ github.ref_name }}"
